// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABBSc9UmaM6U712ljjyRzhWKZplKZA6gA',
    appId: '1:493280157969:web:0b4e8d64310d0dd95c2cb0',
    messagingSenderId: '493280157969',
    projectId: 'erzurumspor-app',
    authDomain: 'erzurumspor-app.firebaseapp.com',
    storageBucket: 'erzurumspor-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADudwJOQmrxQl4mh9mx5cHwCpAVlyFQ90',
    appId: '1:493280157969:android:b098e88e30102ff65c2cb0',
    messagingSenderId: '493280157969',
    projectId: 'erzurumspor-app',
    storageBucket: 'erzurumspor-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdI4P2p2fif2uN4L1Y18tt0Ej2JNeJByg',
    appId: '1:493280157969:ios:f73c0fed53e2fba15c2cb0',
    messagingSenderId: '493280157969',
    projectId: 'erzurumspor-app',
    storageBucket: 'erzurumspor-app.firebasestorage.app',
    iosBundleId: 'com.example.erzurumsporfk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdI4P2p2fif2uN4L1Y18tt0Ej2JNeJByg',
    appId: '1:493280157969:ios:f73c0fed53e2fba15c2cb0',
    messagingSenderId: '493280157969',
    projectId: 'erzurumspor-app',
    storageBucket: 'erzurumspor-app.firebasestorage.app',
    iosBundleId: 'com.example.erzurumsporfk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABBSc9UmaM6U712ljjyRzhWKZplKZA6gA',
    appId: '1:493280157969:web:c84107249c0bd8ec5c2cb0',
    messagingSenderId: '493280157969',
    projectId: 'erzurumspor-app',
    authDomain: 'erzurumspor-app.firebaseapp.com',
    storageBucket: 'erzurumspor-app.firebasestorage.app',
  );
}
